select task_id,
       comment,
       plan_visit_at,
       started_at,
       finished_at,
       inspection_id,
       inspection_type,
       inspection_resolution,
       inspection_limit_reason,
       inspection_method,
       inspection_method_by,
       inspection_reason_type,
       inspection_reason_description,
       inspection_is_restriction_checked,
       inspection_is_violation_detected,
       inspection_is_expense_available,
       inspection_violation_description,
       inspection_is_unauthorized_consumers,
       inspection_unauthorized_description,
       inspection_unauthorized_explanation,
       inspection_inspect_at,
       inspection_energy_action_at,
       brigade_id,
       brigade_inspectors,
       object_id,
       object_address,
       object_have_automaton,
       subscriber_id,
       subscriber_account_number,
       subscriber_surname,
       subscriber_name,
       subscriber_patronymic,
       subscriber_phone_number,
       subscriber_email,
       subscriber_inn,
       subscriber_birth_date,
       subscriber_status
from finished_tasks
where $1 <= finished_at
  and finished_at < $2;
